### PR TITLE
Demonstration on how to use an appendix in the documentation

### PR DESCRIPTION
**Pull request by TheCedarPrince**
I added a small update to the documentation on how to add an appendix to the book you create. Anything else I should add in here @rikhuijzer ?

### CODE REVIEW

**Comment by rikhuijzer** [comment]
Isn't this obvious? It is also used at the Julia Data Science book

**Comment by TheCedarPrince** [comment]
Hey @rikhuijzer ! I guess I didn't find it obvious as I spent about 30 - 45 minutes trying to figure out how to add an appendix. First tried seeing if I needed to modify Books.jl to make a PR then I tried looking into the pandoc specification. Sure enough, in the spec was where it explained how to make an Appendix. I figured that if I, who loves pandoc, didn't know exactly where to look first, it may be useful to have in the docs. But if you think it is not useful, feel free to close. Hope you are having a great day!

**Comment by rikhuijzer** [comment]
Given that this PR also fails, let's agree to disagree.

**Comment by TheCedarPrince** [comment]
Fair enough @rikhuijzer ! Would you be opposed to a separate PR on adding a small note in the Demo Section of the docs in "Other Notes" on how to add an appendix? I still think it would be useful to have it documented but see your point about not having it as a separate new component of the docs.

**Comment by rikhuijzer** [comment]
I think that a better solution would be to create a minimal example template repository which people can easily copy/clone. This repository can then include an appendix by default. What do you think?

**Comment by TheCedarPrince** [comment]
Oh I think that is an excellent idea. I will chat with you about this on Zulip.

**Pull request closed without merging**
